[package]
name = "wpactrl"
description = "wpa_supplicant control interface library"
license = "MIT"
license-file = "LICENSE"
repository = "https://github.com/sauyon/wpa-ctrl-rs"
version = "0.3.0"
authors = [ "Sauyon Lee <s@uyon.co>", "Steven Pease <peasteven@gmail.com>" ]

[dependencies]
failure = "0.1"
libc = "0.2"
lazy_static = "1.0.0"
#dbus = "0.5.2"

[build-dependencies]
cc = "1.0"
