[package]
name = "wpactrl"
description = "wpa_supplicant control interface library"
license-file = "LICENSE"
repository = "https://github.com/sauyon/wpa-ctrl-rust"
version = "0.1.1"
authors = [ "Sauyon Lee <s@uyon.co>" ]

[dependencies]
libc = "0.2"
#dbus = "0.5.2"

[build-dependencies]
gcc = "0.3"
