[package]
name = "wpactrl"
description = "wpa_supplicant control interface library"
license-file = "LICENSE"
repository = "https://github.com/sauyon/wpa-ctrl-rs"
version = "0.2.1"
authors = [ "Sauyon Lee <s@uyon.co>" ]

[dependencies]
failure = "0.1"
libc = "0.2"
#dbus = "0.5.2"

[build-dependencies]
cc = "1.0"
