[package]
name = "wpactrl"
description = "wpa_supplicant control interface library"
license = "MIT"
license-file = "LICENSE"
version = "0.1.0"
authors = [ "Sauyon Lee <s@uyon.co>" ]

[dependencies]
libc = "0.2.0"
#dbus = "0.5.2"
